services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: c2impress-sparql_app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
