#!/bin/bash

# Function to handle docker-compose commands
function docker_compose() {
  docker compose "$@"
}

# Check for 'up', 'down', and 'build' commands
case "$1" in
  up)
    docker_compose up -d
    ;;
  down)
    docker_compose down
    ;;
  build)
    docker_compose build
    ;;
  *)
    # Pass any other commands to be run inside the container
    docker exec -it c2impress-sparql_app "$@"
    ;;
esac
